server:
  port: 3333
  address: 0.0.0.0

spring:
  application:
    name: soul-eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:  http://eureka.xsoft.com/eureka/

logging:
  level:
    root: info
    org.dromara.soul: debug
  path: "./logs"

