server:
  port: 9800
  address: 0.0.0.0

spring:
   main:
     allow-bean-definition-overriding: true
   application:
     name: soul-executor
   profiles:
     active: dev
   redis:
     host: localhost
     password: 123456
     port: 6379
   influxdb:
        url: http://localhost:8086
        username: test
        password: test
        database: test
        retention-policy: autogen
        connect-timeout: 10
        read-timeout: 30
        write-timeout: 10
   zookeeper:
        url : localhost:2181
        sessionTimeout: 5000
        connectionTimeout : 2000
        serializer : KryoSerializer
soul:
  bufferSize: 2048
  timeVerify:
    timeDelay : 10
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

logging:
    level:
        root: info
        org.springframework.boot: info
        org.apache.ibatis: info
        org.dromara.soul.bonuspoint: info
        org.dromara.soul.lottery: debug
        org.dromara.soul: debug
    path: "./logs"
    pattern:
      console: "%boldMagenta(%d{yyyy-MM-dd HH:mm:ss})  [%p]  %highlight(%C:%L)  : %m %n"
